kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: vlc
  labels:
    app: vlc
spec:
  to:
    kind: Service
    name: vlc-hls
  tls: null
  port:
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: vlc-hls
  labels:
    app: vlc
spec:
  type: NodePort
  selector:
    app: vlc
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30680
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: vlc
  labels:
    app: vlc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vlc
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: vlc
    spec:
      containers:
      - name: vlc-origin
        imagePullPolicy: Always
        image: "quay.io/narlabs/fnr-vlc:latest"
        command: ["/bin/sh","-c"]
        args: ["vlc fnr_sample.mp4 --sout '#standard{access=http,mux=ts,dst=:8080}' -I dummy"]
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
